version: "3"
services:
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: postgres-standalone
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5433
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    restart: unless-stopped
  # APP*****************************************
  springbootapp:
    image: davidsalatic6/sports-club:server
    network_mode: bridge
    container_name: sports-club
    expose:
      - 8082
    ports:
      - 8082:8082
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres

  angularapp:
    image: davidsalatic6/sports-club:front
    network_mode: bridge
    container_name: sports-club-front
    expose:
      - 4200
    ports:
      - 4200:80
    restart: unless-stopped
volumes:
  postgres-data: